# -*- coding: utf-8 -*-
"""NM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orOZLlOAzLFnLUlL4uQ0MgFWz6scIqz0
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("netflix_titles.csv")
df.head(10)
df.shape  # number of rows and columns
df.info()  # check for missing values and data types
import pandas as pd
df = pd.read_csv("netflix_titles.csv")
df.head(10)
df.shape  # number of rows and columns
df.info()  # check for missing values and data types

df.isnull().sum()

df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df['date_added'] = df['date_added'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Unknown')
df['duration'] = df['duration'].fillna('Unknown')

df.isnull().sum()

type_counts = df['type'].value_counts()
print(type_counts)

top_countries = df['country'].value_counts().head(5)
print(top_countries)

top_directors = df['director'].value_counts().head(10)
print(top_directors)

from collections import Counter

# Split genre strings and flatten
all_genres = ','.join(df['listed_in']).split(', ')
genre_counts = Counter(all_genres)
top_genres = genre_counts.most_common(10)

print(top_genres)

release_trend = df['release_year'].value_counts().sort_index()
print(release_trend)

import matplotlib.pyplot as plt
import seaborn as sns

# Optional: improves plot style
sns.set(style="whitegrid")

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='type', palette='Set2')
plt.title('Number of Movies vs TV Shows on Netflix')
plt.xlabel('Type')
plt.ylabel('Count')
plt.show()

top_5_countries = df['country'].value_counts().head(5)

plt.figure(figsize=(6,6))
plt.pie(top_5_countries, labels=top_5_countries.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("pastel"))
plt.title('Top 5 Countries Producing Netflix Content')
plt.axis('equal')
plt.show()

release_trend = df['release_year'].value_counts().sort_index()

plt.figure(figsize=(10,5))
sns.lineplot(x=release_trend.index, y=release_trend.values, marker='o', color='teal')
plt.title('Netflix Content Released Per Year')
plt.xlabel('Release Year')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

!pip install wordcloud

from wordcloud import WordCloud

# Word Cloud of all genres
genres = ' '.join(df['listed_in'])

wc = WordCloud(width=800, height=400, background_color='white').generate(genres)

plt.figure(figsize=(10,5))
plt.imshow(wc, interpolation='bilinear')
plt.axis('off')
plt.title('Most Frequent Genres')
plt.show()

